### PR TITLE
Add maintenance notice

### PR DESCRIPTION
**Pull request by christian-bromann**
It seems that Sauce Labs is not really interested maintaining this project anymore. Therefor I made a fork and will continue maintenance on my account. Feel free to merge this PR adding a notice on maintenance of the project.

Cheers

### CODE REVIEW

**Comment by titusfortner** [comment]
@christian-bromann would it make more sense for us to transfer the repo to you instead of forking if we can't maintain it?
(cc @diemol)

**Comment by christian-bromann** [comment]
> would it make more sense for us to transfer the repo to you instead of forking if we can't maintain it?

I am still in the process to get the `cddl` repo transferred to me, don't want to go through legal for this one.

**Comment by diemol** [comment]
@christian-bromann we are interested in maintaining it, however we do not have the time. Is there a PR you'd like to merge? If so, I can happily run the tests and check if the docs are still working after merging it.

**Comment by christian-bromann** [comment]
I am interested pushing forward some new features and keep up with dependency updates. Sauce can continue use the new package I released as [`docusaurus-theme-github-codeblock`](https://www.npmjs.com/package/docusaurus-theme-github-codeblock).

**Comment by diemol** [comment]
I will start maintaining this.

**Pull request closed without merging**
