### PR TITLE
fix: remove url import breaking with docusaurus 2.0.0-beta.18

### LINKED ISSUE #18: cannot resolve `url` with docusaurus 2.0.0-beta.18
Hey thanks for the repo, was looking to implement this but always nice when I don't have to.

Just tried using against latest `2.0.0-beta.18` of docusaurus v2.

Fails when loading a code block with the following.

```
Compiled with problems:

ERROR in ./node_modules/@saucelabs/theme-github-codeblock/build/theme/ReferenceCodeBlock/index.js 26:14-28

Module not found: Error: Can't resolve 'url' in '/Users/saf/dev/pactflow/docs.pactflow.io/website/node_modules/@saucelabs/theme-github-codeblock/build/theme/ReferenceCodeBlock'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "url": require.resolve("url/") }'
	- install 'url'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "url": false }
	```
	
Removing the import from this line in the bundled output resolves it and it works fine

https://github.com/saucelabs/docusaurus-theme-github-codeblock/blob/3e94f0555f93f97fbb4db46673905dc6b9fe1635/src/theme/ReferenceCodeBlock/index.tsx#L1

Happy to submit a pull request

### PR DESCRIPTION
**Pull request by YOU54F**
fixes #18

Confirmed working (published under my scope to temporarily test)

👍🏾

### CODE REVIEW

**Comment by YOU54F** [comment]
@christian-bromann hey man, any chance I could get you to look at a couple of these PR's when you get some free time 👍🏾

**Comment by christian-bromann** [comment]
@YOU54F Hey 👋  unfortunately I am not maintaining this package nor any other Sauce Labs packages anymore. Please ping @diemol @boneskull or @discombobulateme

**Comment by YOU54F** [comment]
> @YOU54F Hey 👋 unfortunately I am not maintaining this package nor any other Sauce Labs packages anymore. Please ping @diemol @boneskull or @discombobulateme

Ahh no worries man, just saw you head up WDIO 👌🏾.

Nice!

Well if I can't get sorted with these changes, I will just crack on with my own little package. Thanks buddy

**Comment by discombobulateme** [comment]
Hi @YOU54F we are on it :) thank you so much for your contribution! Give me a day to figure out ownership restructure...

**Review by boneskull — CHANGES_REQUESTED** [review]
@YOU54F Thanks! Can you please remove your changes to `package-lock.json` from the PR?

The build is failing due to a reduction in coverage (which will always happen if code is only removed).  This check should probably be disabled, but don't worry about it.

**Comment by YOU54F** [comment]
> @YOU54F Thanks! Can you please remove your changes to `package-lock.json` from the PR?
> 
> The build is failing due to a reduction in coverage (which will always happen if code is only removed). This check should probably be disabled, but don't worry about it.

cheers dude! have done

**Comment by discombobulateme** [comment]
Hi @YOU54F , we cannot accept a PR before the new owners properly understand the package and get better testing coverage as it will directly affect at least one of our websites. I am sorry to make you wait, but we don't want things to break :) I hope you understand. We will, as soon as possible, go back to that. 
If you need to update it to fix your own project, please feel free to fork it in the meantime.

**Comment by YOU54F** [comment]
Hey @discombobulateme 

No problem at all, totally appreciate the cautious approach! I'm still experimenting at the moment with cool ways to display our code, so will borrow some ideas from this project into my own.

Thanks!

Will close down these PR's for now to avoid the noise

**Comment by homotechsual** [comment]
@YOU54F what did you end up using for this solution, this plugin appears at this stage to be unmaintained so I'm wondering whether I should start up a fork of this plugin or go another direction.

**Comment by YOU54F** [comment]
I published as a fork quite a while ago

https://www.npmjs.com/package/@you54f/theme-github-codeblock and we are using it on our docs.pactflow.io and docs.pact.io sites

**Comment by homotechsual** [comment]
Thanks - can I list that in the plugin directory here: https://docusaurus.community/plugindirectory ?

**Comment by YOU54F** [comment]
There is also a fork more recently created linked to this thread

https://github.com/Uniswap/docs/pull/526

**Comment by homotechsual** [comment]
Ok - I might pick one of those up and publish a new version and actively maintain it as I need the functionality 👍

**Comment by YOU54F** [comment]
> Thanks - can I list that in the plugin directory here: https://docusaurus.community/plugindirectory ?

Probably best not too, as the code isn't public (I've since deleted the fork), so it's a bit of a dangler of an npm package.

Using uniswaps fork looks like a good go for now :)

Hopefully SauceLabs maintainers can give this repo a necessary tickle and then it saves us having forks arounds

**Comment by homotechsual** [comment]
Hopefully @discombobulateme is SauceLabs interesting in maintaining this or would it being forked (and potentially archiving this repo) work better for you?

**Comment by rogeruiz** [comment]
For anyone coming to this thread from #18 and wonders how to fix this in their usage of the latest version of this plugin from 2021, you can install the `url` package from NPM as part of your project's dependencies and the error of not finding the URL package from Webpack go away. Hope this helps.

Here's what it took for me to install this on a Docusaurus 2+ project.

```diff
diff --git a/package.json b/package.json
index f8f84a21d..eee0a864d 100644
--- a/package.json
+++ b/package.json
@@ -18,6 +18,7 @@
     "@docusaurus/plugin-client-redirects": "2.2.0",
     "@docusaurus/preset-classic": "2.2.0",
     "@easyops-cn/docusaurus-search-local": "^0.33.6",
+    "@saucelabs/theme-github-codeblock": "0.1.1",
     "clsx": "^1.2.1",
     "eslint": "^8.31.0",
     "eslint-config-prettier": "^8.6.0",
@@ -30,6 +31,7 @@
     "react": "^17.0.1",
     "react-dom": "^17.0.1",
     "redocusaurus": "^1.4.0",
+    "url": "0.11.0",
     "url-loader": "^4.1.1"
   },
   "resolutions": {

```

**Comment by diemol** [comment]
@YOU54F we'd like to have a look at this again. I wanted to reopen the PR, but the repository has been deleted. Would you still want to contribute this?

**Comment by YOU54F** [comment]
> @YOU54F we'd like to have a look at this again. I wanted to reopen the PR, but the repository has been deleted. Would you still want to contribute this?

have done now, it was a minor change, happy without the attribution

**Comment by YOU54F** [comment]
> @YOU54F we'd like to have a look at this again. I wanted to reopen the PR, but the repository has been deleted. Would you still want to contribute this?

no

**Pull request closed without merging**
